services:
  base:
    build: ./packages/base
    environment:
      - CONMIRO_HOST=conmiro
      - CONMIRO_PORT=8081
      - PORT=8080
    ports:
      - "8080:8080"
  conmiro:
    build: ./packages/conmiro
    ports: 
      - "8081:8081"
    environment:
      - PORT=8081
    
